### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by TesterlifeRaymond** [elliotchance/pie#162]
Hello, dear author. I have the following problems while using pie,
definition:
//go:generate pie Items.*
  type Items []Item

The file after generate prompts an error, and the compilation error is as follows.

question:
invalid operation: lookingFor == s (struct containing pie.Ints cannot be compared)
invalid operation: s == element (struct containing pie.Ints cannot be compared)
invalid operation: ss[i] == rhs[i] (struct containing pie.Ints cannot be compared)
invalid map key type Items

**Comment by elliotchance** [comment]
`Items.*` will generate *all* functions, including functions that rely on comparisons. However, `Item` is not a structure that can be compared (using the `==` operator) becuase Item contains a slice and that is not allowed in Go. You have a few options:

1. Only include functions you need, like `//go:generate pie Items.Map` (without functions that require a comparison).
2. Implement your own comparitor for `Item` - see https://github.com/elliotchance/pie#custom-equality
3. Modify `Item` so it only contains elements that can be compared with the `==` operator.

**Comment by TesterlifeRaymond** [comment]
thx. @elliotchance I'll take a look at the specific implementation and processing methods. Thank you again
