### ISSUE TITLE
Diff: unexpected behaviour

### ISSUE THREAD

**Issue by andriyor** [elliotchance/pie#169]
```
firstSlice := pie.Ints{1, 2, 3, 3, 4, 4}
secondSlice := pie.Ints{3, 4, 5, 4, 6}
fmt.Println(firstSlice.Diff(secondSlice))
```

panic: runtime error: slice bounds out of range [5:4]

**Comment by elliotchance** [comment]
@andriyor happy to accept a PR if you have a fix 😄

**Comment by istudko** [comment]
https://github.com/elliotchance/pie/blob/master/pie/ints_pie.go#L143 <-- this line is causing the problem

**Comment by istudko** [comment]
@elliotchance I raised the PR, waiting for a review.
