### ISSUE TITLE
remove element by value and by index

### ISSUE THREAD

**Issue by ismlsmile** [elliotchance/pie#180]
Could I remove an element by its value and index ?

**Comment by elliotchance** [comment]
I'm not sure if you mean you wish to remove an element when its matches an index *and* it's value, or if you mean you want independent processes to do either.

There is no function for removing by index (although, there should be). If you want to remove by value, you can use `Filter` or `FilterNot`.

**Comment by chocolacula** [comment]
I am ready to implement a function for removing by index. I think issue https://github.com/elliotchance/pie/issues/171 is related to this one. @elliotchance approve or correct me please and I'll do that as soon as I can.

**Comment by elliotchance** [comment]
Go for it. The linked diff was against pie v1 which I'm not supporting anymore.

**Comment by chocolacula** [comment]
Added in https://github.com/elliotchance/pie/pull/194

**Comment by chocolacula** [comment]
@elliotchance perhaps, the issue could be closed because removing by index was implemented, and filtering function already exists.

**Comment by elliotchance** [comment]
@chocolacula yeah, good point
