### ISSUE TITLE
Add inline documentation

### ISSUE THREAD

**Issue by royhadad** [elliotchance/pie#186]
When using javascript arrays, we get the following documentation for each method:
![Screenshot 2023-02-01 at 11 50 09](https://user-images.githubusercontent.com/39004075/216009192-d990d806-7a10-4edd-80dc-8094ca974705.png)

When using this library, we don't get any docs:
![Screenshot 2023-02-01 at 11 51 34](https://user-images.githubusercontent.com/39004075/216009553-d162e6ff-11f0-450a-9f4e-ad45cb71399e.png)

Proposed feature:
Add short documentation for the methods in the package

**Comment by elliotchance** [comment]
Yes, you're right. We have docs for all functions, such as: https://github.com/elliotchance/pie/blob/master/v2/map.go

But they need to be copied to the chained versions: https://github.com/elliotchance/pie/blob/master/v2/of.go

Happy to accept a PR for this... 😄
