### ISSUE TITLE
func Subslice(int, int) SliceType

### ISSUE THREAD

**Issue by elliotchance** [elliotchance/pie#24]
Subslice returns a new slice that starts an index and contains len items. The parameters must both be zero or positive and be in a valid range.

**Comment by ougwen1235** [comment]
@elliotchance the second parameter means len? How about end?

**Comment by elliotchance** [comment]
Yes, you're right. The second parameters should be the end so that it's consistent with the Go slices.

**Comment by ougwen1235** [comment]
I'll try to send a PR as soon as possible.

**Comment by ougwen1235** [comment]
@elliotchance What if one parameter is in a valid range but the other one is out of valid range? Is nil a good choice?

**Comment by elliotchance** [comment]
Actually, I wonder if this function is needed at all. `Subslice(x, y)` would be a more verbose way to use `[x:y]` which returns the same type of slice anyway.

So there's no need to copy Go's slice rules. I think it should return *any* element that exist in the range provided (which may be zero items). So either parameter can be out of bounds.

**Comment by ougwen1235** [comment]
As for the name, I prefer SubSlice to Subslice. How about you?

**Comment by elliotchance** [comment]
Sure. That's fine.
