### ISSUE TITLE
Shift() and Unshift()

### ISSUE THREAD

**Issue by elliotchance** [elliotchance/pie#37]

**Comment by ougwen1235** [comment]
What does Shift return, the rest slice after removing the first element?

**Comment by elliotchance** [comment]
That's correct. `Shift` would need to return two values. The first is the shifted value (or zero) and the second return value would be `DropTop(1)`.

**Comment by ougwen1235** [comment]
I wonder whether the shifted value is needed or not. Maybe just the rest slice is needed? Moreover, if it return two values, it can't be chained anymore.

**Comment by elliotchance** [comment]
Shift should return the value that was shifted. If the user doesn't care about the shifted value or they wanted to continue chaining they should use `DropTop(1)` instead.

**Comment by ougwen1235** [comment]
OK. I will make a pr.
