### ISSUE TITLE
Insert()

### ISSUE THREAD

**Issue by elliotchance** [elliotchance/pie#43]
Inserts a value at an index

**Comment by rafa-acioly** [comment]
Hi @elliotchance, the insert should change the current slice or retrieve a new one?

**Comment by elliotchance** [comment]
All functions in pie are immutable on purpose, so they must allocate if they intended to change the value returned.

Insert would require an index and zero or more elements:

```go
pie.Strings{"Hello", "Smith"}.Insert(1)
// pie.Strings{"Hello", "Smith"} // no allocation needed

pie.Strings{"Hello", "Smith"}.Insert(1, "Bob")
// pie.Strings{"Hello", "Bob", "Smith"}

pie.Strings{"Hello", "Smith"}.Insert(1, "Bob", "Robert")
// pie.Strings{"Hello", "Bob", "Robert", "Smith"}
```

**Comment by rafa-acioly** [comment]
This looks strange to me @elliotchance, the example:

```go
pie.Strings{"Hello", "Smith"}.Insert(1, "Bob", "Robert")
// pie.Strings{"Hello", "Bob", "Robert", "Smith"}
```

Resuming we are saying "insert Bob and Robert at index 1" but Robert will be at index 2 🤔 
what do you think of only accepting zero or 1 element?

**Comment by elliotchance** [comment]
I think of it as it is inserting a slice (not an element) at an index. So the index would really be "insert starting at this index" which holds true for zero or more elements. It could be expressed more explicitly as:

```go
pie.Strings{"Hello", "Smith"}.Insert(1, pie.Strings{"Bob", "Robert"})
```

However, that syntax is annoying because I would imagine in most cases someone would only insert a single element.

To your point, I read it as "insert Bob and Robert after index 1". I think it's more likely to be used with the splat operator when dealing with slices:

```go
nameParts := pie.Strings{"Bob", "Robert"}
pie.Strings{"Hello", "Smith"}.Insert(1, nameParts...)
// pie.Strings{"Hello", "Bob", "Robert", "Smith"}
```

Does that make sense?

**Comment by rafa-acioly** [comment]
totally, i'll try to send a `PR` as soon as possible :)
