### ISSUE TITLE
Reduce()

### ISSUE THREAD

**Issue by DylanMeeus** [elliotchance/pie#87]
Add a function to reduce elements in a collection to a scalar value. Think of something like this:

```
nums := []int{1,2,3,4,5}
res := reduce(nums, func(a, b int) int{
      return a + b
}
```

Similar to how a reduce function would work in e.g: Haskell, Java, Python, ...

- I'll try to add this function to the lib, but wanted to communicate my intention beforehand.

**Comment by elliotchance** [comment]
Yep. This makes perfect sense to me. Looking forward to the PR :)
