### ISSUE TITLE
Median in O(n) average performance

### ISSUE THREAD

**Issue by Deleplace** [elliotchance/pie#91]
Hi, Median currently does alloc + Sort, for a total cost O(n log n).

I think we can achieve alloc + custom code, for a total cost O(n) on average.

Shall I do impl, tests, benchmarks, and PR? This would be mergeable if the large case is improved, and the small case not degraded.

**Comment by Deleplace** [comment]
What I have in mind, instead of a full sort, is a quicksort-like algo that makes only 1 recursive call instead of 2.

I say "on average" for the exact same reason that quicksort is O(n log n) "on average".

**Comment by elliotchance** [comment]
If you can improve the performance that would be great. However, I'm not sure how you would achieve a median without a sort and that's why its currently at O(n log n).

**Comment by Deleplace** [comment]
Here is how: let's take QuickSort as reference.

Quicksort makes **_h_** "passes", and **_h_** is on average ~log(**_n_**). Each pass makes 2 recursive calls. As each "pass" traverses the whole slice (2 * 1/2, then 4 * 1/4, etc.) the total cost is O(n . log(**_n_**)) on average.

The median search is similar, but makes only 1 recursive call because it's only interested in either the left part of the pivot, or the right part of the pivot. If each pass is, say, half of the previous pass, then the total cost is **_n_** + **_n_**/2 + **_n_**/4 + ... = 2**_n_**.

This analysis still works even if each pass is not exactly half of the previous pass. The edge case would be a big slice with only one of two distinct values, leading to dedraded quadratic run time.

![Median algo](https://user-images.githubusercontent.com/13508141/57519199-0499a480-731b-11e9-834b-67a4bc19eb27.png)

**Comment by Deleplace** [comment]
Here is the implementation : https://github.com/Deleplace/forks-pie/blob/issues/91-median-linear-algo/functions/median.go

and the benchmarks : 
- https://github.com/Deleplace/forks-pie/blob/issues/91-median-linear-algo/pie/ints_bench_test.go
- https://github.com/Deleplace/forks-pie/blob/issues/91-median-linear-algo/pie/float64s_bench_test.go

In this snippet
```
	for i := 0; i < b.N; i++ {
		// m := a.MedianOld()
		// m := a.medianCheck()
		m := a.Median()
		sinkInts += m
	}
```
`MedianOld()` benchmarks the old implementation, `medianCheck()` runs old and new implementations on many inputs and checks that the results are the same, and `Median()` benchmarks the new implementation.

The results (with [benchstat](https://godoc.org/golang.org/x/perf/cmd/benchstat)) show that the new implementation is much faster:
```
name                  old time/op  new time/op  delta
FloatMedianSmall-12    826ns ± 3%   262ns ± 6%  -68.25%  (p=0.000 n=10+10)
FloatMedianMedium-12  71.9µs ± 2%   6.6µs ±12%  -90.78%  (p=0.000 n=10+10)
FloatMedianLarge-12    180ms ± 3%    16ms ± 4%  -91.34%  (p=0.000 n=10+10)
IntMedianSmall-12      732ns ± 3%   262ns ± 7%  -64.20%  (p=0.000 n=10+10)
IntMedianMedium-12    65.6µs ± 3%  10.4µs ± 5%  -84.16%  (p=0.000 n=10+10)
IntMedianLarge-12      165ms ± 3%    15ms ± 1%  -91.06%  (p=0.000 n=10+8)
```

Shall I keep only the new impl and make a PR?

**Comment by elliotchance** [comment]
Wow, that’s great! Yes, please put in a PR for the faster implementation.
