### ISSUE TITLE
Append can be destructive

### ISSUE THREAD

**Issue by Deleplace** [elliotchance/pie#97]
One important goal of Pie is "Functions never modify inputs".

However, as long as `Append` is a wrapper of the built-in `append`, the result will often share its underlying array with the input receiver, which leads to erratic behavior. The test below fails:

```
package pie

import (
	"testing"
)

func TestAppendNonDestructive(t *testing.T) {
	ab := Strings{"A", "B"}
	if x, expected := ab.Join(""), "AB"; x != expected {
		t.Errorf("Expected %q, got %q", expected, x)
	}

	abc := ab.Append("C")
	aby := ab.Append("Y")
	if x, expected := abc.Join(""), "ABC"; x != expected {
		t.Errorf("Expected %q, got %q", expected, x)
	}
	if x, expected := aby.Join(""), "ABY"; x != expected {
		t.Errorf("Expected %q, got %q", expected, x)
	}

	abcd := abc.Append("D")
	abcz := abc.Append("Z")
	if x, expected := abcd.Join(""), "ABCD"; x != expected {
		t.Errorf("Expected %q, got %q", expected, x)
	}
	if x, expected := abcz.Join(""), "ABCZ"; x != expected {
		t.Errorf("Expected %q, got %q", expected, x)
	}
}
```

I suggest a small modification to `Append`, to make sure a new slice a always allocated.

**Comment by Deleplace** [comment]
In vanilla Go it is fine to construct a slice of N elements by calling `append` N times, for a total cost O(N). Each call has amortized cost O(1).

This is no longer true with the modification suggested above, and constructing a slice of N elements by calling `Append` N times, will result in a total cost O(N^2).

To preserve performance, alternative ways of constructing large slices should be prefered (e.g. initialize data in vanilla Go, then convert to Pie slice).

**Comment by elliotchance** [comment]
I never thought about it like that. I had to run the test to understand what you meant. This is pretty crude, but wouldn't this do the trick (at least it passes the test now)?

```go
func (ss Strings) Append(elements ...string) Strings {
	ss2 := make(Strings, len(ss) + len(elements))
	for i := 0; i < len(ss); i++ {
		ss2[i] = ss[i]
	}
	for i := 0; i < len(elements); i++ {
		ss2[i+len(ss)] = elements[i]
	}
	return ss2
}
```

With O(n).

**Comment by Deleplace** [comment]
Yes, exactly! The loops are equivalent to calling the built-in `copy`. And there's a trick to force allocating new memory with `append`, which is to append to an empty or nil slice.

I'll create a PR with the test + the fix.
