### ISSUE TITLE
SortWith and SortStableWith, for Structs

### ISSUE THREAD

**Issue by Deleplace** [elliotchance/pie#98]
It would be nice to have wrappers to `sort.Slice` and `sort.SliceStable`.

2 advantages:
- create a new slice to be sorted and returned, instead of sorting in-place in a destructive manner;
- instead of parameter `less` of type `func(i, j int) bool`, we can choose the more convenient signature `less func(a, b ElementType) bool`.

**Comment by elliotchance** [comment]
Yes, absolutely.

**Comment by elliotchance** [comment]
Also see #22

**Comment by Deleplace** [comment]
Indeed, this is almost a dupe of #22. Thanks!

I'll give a shot at implementing it.
